var jsCategories = [
    { value: 0, text: "Unknown", color: "#dddddd" },
    { value: 1, text: "Doctor", color: "#52aa8e" },
    { value: 2, text: "HCP", color: "#D14FC6" },
    { value: 4, text: "Patient", color: "#e82d4f" },
    { value: 9, text: "Caregiver\/Advocate", color: "#cec07a" },
    { value: 10, text: "Researcher\/Academic", color: "#759ECC" },
    { value: 38, text: "Journalist\/Media", color: "#6a9c9c" },
    { value: 11, text: "Individual Other Healthcare", color: "#823E45" },
    { value: 5, text: "Individual Other Non-healthcare", color: "#6C4587" },
    { value: 12, text: "Org. Provider", color: "#63B142" },
    { value: 13, text: "Org. Research\/Academic", color: "#4D652F" },
    { value: 14, text: "Org. Government", color: "#CF4471" },
    { value: 8, text: "Org. Pharma", color: "#465E73" },
    { value: 26, text: "Org. Media", color: "#682de6" },
    { value: 15, text: "Org. Advocate\/Support", color: "#CA7FA8" },
    { value: 3, text: "Org. Other Healthcare", color: "#B67139" },
    { value: 6, text: "Org. Other Non-healthcare", color: "#8774DA" },
    { value: 7, text: "Spam", color: "#dddddd" },
    { value: 0, text: "Unkn             own", color: "#dddddd" }
];
var jsSelectableCategories = [
    { value: 1, text: "Doctor", color: "#52aa8e" },
    { value: 2, text: "HCP", color: "#D14FC6" },
    { value: 4, text: "Patient", color: "#e82d4f" },
    { value: 9, text: "Caregiver\/Advocate", color: "#cec07a" },
    { value: 10, text: "Researcher\/Academic", color: "#759ECC" },
    { value: 38, text: "Journalist\/Media", color: "#6a9c9c" },
    { value: 11, text: "Individual Other Healthcare", color: "#823E45" },
    { value: 5, text: "Individual Other Non-healthcare", color: "#6C4587" },
    { value: 12, text: "Org. Provider", color: "#63B142" },
    { value: 13, text: "Org. Research\/Academic", color: "#4D652F" },
    { value: 14, text: "Org. Government", color: "#CF4471" },
    { value: 8, text: "Org. Pharma", color: "#465E73" },
    { value: 26, text: "Org. Media", color: "#682de6" },
    { value: 15, text: "Org. Advocate\/Support", color: "#CA7FA8" },
    { value: 3, text: "Org. Other Healthcare", color: "#B67139" },
    { value: 6, text: "Org. Other Non-healthcare", color: "#8774DA" },
    { value: 7, text: "Spam", color: "#dddddd" }
];
var defaultPillBg = "#dddddd";
var jsBgColors = [
    "bg52aa8e",
    "bgD14FC6",
    "bge82d4f",
    "bgcec07a",
    "bg759ECC",
    "bg6a9c9c",
    "bg823E45",
    "bg6C4587",
    "bg63B142",
    "bg4D652F",
    "bgCF4471",
    "bg465E73",
    "bg682de6",
    "bgCA7FA8",
    "bgB67139",
    "bg8774DA",
    "bgdddddd"
];
